# Generated by Django 5.2 on 2025-04-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собранная сумма'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='donors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество доноров'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Дата завершения сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Целевая сумма'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='occasion',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('new_year', 'Новый год'), ('other', 'Другое')], max_length=50, verbose_name='Повод'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.collect', verbose_name='Сбор'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Донор'),
        ),
    ]
