# Generated by Django 5.2 on 2025-04-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collect_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name': 'сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='donor',
            new_name='author',
        ),
    ]
