# Generated by Django 5.2 on 2025-04-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_collect_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='author',
            new_name='donor',
        ),
    ]
