# Generated by Django 5.2 on 2025-04-19 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_collect_options_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentcomment',
            unique_together={('payment', 'user')},
        ),
    ]
