# Generated by Django 5.2 on 2025-04-19 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paymentcomment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentlike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='paymentcomment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paymentlike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='paymentcomment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payment'),
        ),
        migrations.AlterField(
            model_name='paymentlike',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentcomment',
            constraint=models.UniqueConstraint(fields=('payment', 'user'), name='unique_comment'),
        ),
        migrations.AddConstraint(
            model_name='paymentlike',
            constraint=models.UniqueConstraint(fields=('payment', 'user'), name='unique_like'),
        ),
    ]
