# Generated by Django 5.2 on 2025-04-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paymentcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcomment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.payment'),
        ),
    ]
