# Generated by Django 5.2 on 2025-04-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_paymentlike_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'комментарий на платеж', 'verbose_name_plural': 'Комментарии на платежи'},
        ),
        migrations.AlterModelOptions(
            name='paymentlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'лайк платежа', 'verbose_name_plural': 'Лайки на платежи'},
        ),
        migrations.AddField(
            model_name='collect',
            name='short_link',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
